services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5050:5050

# Note: The proxy service is only necessary if you are running a Shannon
# localnet and are unable to use the docker network in bridge mode.
# To use the proxy service you must run the following command on the host
# to establish a reverse proxy such that docker services in the composition
# will be able to port forward to the localnet services exposed on the host:
# ssh -o StrictHostKeyChecking=no -N -R 26657:localhost:26657 proxyuser@localhost -p 2222
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy.dockerfile
    environment:
      - USER_NAME=proxyuser
      - USER_PASSWORD=proxypass
    ports:
      - "2222:22"
    volumes:
      - ~/.ssh/id_rsa.pub:/home/proxyuser/.ssh/authorized_keys

  subquery-node:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
      args:
        # NOTE: this only applies when WATCH is not true on environment variables
        # allow switching between dotenv file
        # set nothing or comment to use .env or set develop to use .env.develop
        # you can create your own .env.<something> and specify <something> as NODE_ENV value.
        NODE_ENV:
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      START_BLOCK: 1
      # anything that is not "true" will avoid start nodemon
      WATCH: true
      # this will manage which dotenv file will be used on every reload
      NODE_ENV: develop
    volumes:
      - ./:/app
      - ignore_dist:/app/dist
      - ignore_types:/app/src/types
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --db-schema=app
      - --workers=1
      - --batch-size=30
      - --unfinalized-blocks=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000

volumes:
  ignore_dist: {}
  ignore_types: {}
  postgres_data:
    driver: local
